export const CONFIG = {
  REF_H: 225,
  yTopDist: 130,
  yMidDist: 85,
  sizeAtTop: 22.5,
  sizeAtMid: 45,
  sizeAtBottom: 67.5,
  sheepTotal: 30,
  targetVisible: 20,
  targetOffscreen: 10,
  wrapMargin: 80,
  xfadeSeconds: 0.45,
  introFadeSeconds: 0.8,
  bgVideoPath: "assets/bg/grassland.MP4",
  sheepFramePrefix: "assets/sheep/sheep_rf",
  sheepFrameCount: 6,
  sheepFrameExt: ".png",
  baseSpeedMin: 14,
  baseSpeedMax: 28,
  wanderTurnChancePerSec: 0.23,
  maxTurnRate: 1.2,
  offscreenReturnBoost: 0.4,
};
